# Generated by Django 4.2.5 on 2024-04-20 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="liker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="post_liked",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_liked",
                to="network.post",
            ),
        ),
    ]
