# Generated by Django 4.2.5 on 2024-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_like_liker_alter_like_post_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
